apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-cloud
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-cloud
  template:
    metadata:
      labels:
        app: multi-cloud
    spec:
      containers:
      - name: multi-cloud
        image: djhope99/cloud-repo:multi-cloud 
        ports:
        - containerPort: 8080
